version: "3.5"
networks:
  bot:
    name: bot

services:
  db:
    container_name: "db"
    networks:
      - bot
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD

  bot:
    container_name: "bot"
    depends_on:
      - db
    networks:
      - bot
    build:
      context: .
      dockerfile: ./cmd/queueBot/Dockerfile
    image: queuebot
    restart: on-failure
    environment:
      - TOKEN
      - HOST
      - PORT
      - USER
      - PASSWORD
      - DBNAME
      - ADMIN_PASSWORD