version: "3"
networks:
  bot:
    external: true

services:
  bot:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - TOKEN=
      - HOST=127.0.0.1
      - PORT=3306
      - USER=
      - PASSWORD=
      - DBNAME=queue_db
      - ADMIN_PASSWORD=
    depends_on:
      - bot-db
    networks:
      - bot

  bot-db:
    image: mysql/mysql-server
    restart: always
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - bot

