version: "3"
networks:
  bot:
    external: true

services:
  bot:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - TOKEN=2057091218:AAG4dtsDK-THlBjpD2CruAd-LhQIWbBnjx0
      - HOST=0.0.0.0
      - PORT=3306
      - USER=richardhere
      - PASSWORD=14112002Rich
      - DBNAME=queue_db
      - ADMIN_PASSWORD=qwerty
    depends_on:
      - bot-db
    networks:
      - bot

  bot-db:
    image: mysql/mysql-server
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=14112002Rich
    ports:
      - "3307:3306"
    networks:
      - bot

