version: "3.5"
networks:
  bot:
    name: bot

services:
  db:
    container_name: "db"
    networks:
      - bot
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw

  bot:
    container_name: "bot"
    depends_on:
      - db
    networks:
      - bot
    build:
      context: ..
      dockerfile: ./cmd/queueBot/Dockerfile
    image: queuebot
    environment:
      - TOKEN=2057091218:AAG4dtsDK-THlBjpD2CruAd-LhQIWbBnjx0
      - HOST=db
      - PORT=3306
      - USER=root
      - PASSWORD=mysqlpw
      - DBNAME=queue_db
      - ADMIN_PASSWORD=qwerty